# Version de Go Alpine como base
FROM golang:1.23.6-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos del proyecto al contenedor
COPY . .

# La API no tiene dependencias externas

# Compilar la aplicación
# CGO_ENABLED=0 para crear un binario estático
# GOOS=linux para asegurar compatibilidad con Linux
RUN CGO_ENABLED=0 GOOS=linux go build -o api1 .

# Exponer el puerto en el que la aplicación escuchará
EXPOSE 8081

# Comando para ejecutar la aplicación
CMD ["./api1"]