apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: mumnk8s
spec:
  type: NodePort
  selector:
    vm.kubevirt.io/name: grafana-valkey-vm
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000