apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: grafana-vm
  namespace: mumnk8s
spec:
  runStrategy: Always
  template:
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: emptydisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/alpine-container-disk-demo:devel
        - name: emptydisk
          emptyDisk:
            capacity: 5Gi